### ISSUE TITLE
Suggest adding a LICENSE file

### ISSUE THREAD

**Issue by jadeallenx** [gyanaggarwal/gen_ord_seq#1]
Just so it's clear to people - I suggest you add a license file to the repository and potentially as a header on your files.  If you'd care for a suggestion, I typically license my own Erlang open source code under the MIT license. At Basho we publish most of our source code under the Apache 2 license.

**Comment by gyanaggarwal** [comment]
Thanks Mark for your suggestion. I will do it ASAP.

**Comment by gyanaggarwal** [comment]
License file has been added and also added license info as header to all the source files
